package com.qi.wechatclient.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qi.wechatclient.bo.Account;
import com.qi.wechatclient.bo.Friend;
import com.qi.wechatclient.chat.enity.MessageInfo;

import com.qi.wechatclient.greendao.AccountDao;
import com.qi.wechatclient.greendao.FriendDao;
import com.qi.wechatclient.greendao.MessageInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig messageInfoDaoConfig;

    private final AccountDao accountDao;
    private final FriendDao friendDao;
    private final MessageInfoDao messageInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Friend.class, friendDao);
        registerDao(MessageInfo.class, messageInfoDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
        messageInfoDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

}
